name: Deploy

on:
  push:
    tags:
      - 'v*.*'


env:
  IMAGE_NAME: build-language-i18n-action

jobs:
  Build_and_push:
    name: Test
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set basic env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION_SHORT=$( echo ${GITHUB_REF#refs/*/} | cut -c 1-2 ) " >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Display tag
        run: |
          echo 'Main:\n' 
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo 'Short:\n'
          echo $RELEASE_VERSION_SHORT
          echo ${{ env.RELEASE_VERSION_SHORT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION_SHORT }}