name: Test

on:
  push:
    branches:
      - dev
  workflow_run:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: text-adi/build-language-i18n-action@dev
      - run: ls -la src/locale/aa/LC_MESSAGES/