name: Test

on:
  push:
    branches:
      - dev


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create file
        run: |
          mkdir src
          echo ${{ vars.TEMPLATE }} > file.po
          ls -la src
      - uses: text-adi/build-language-i18n-action@dev
      - run: ls -la src